#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH="/opt/boxen/homebrew/opt/coreutils/libexec/gnubin:bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/rbenv/plugins/ruby-build/bin:/opt/boxen/nodenv/shims:/opt/boxen/nodenv/bin:/opt/boxen/foreman/bin:/opt/boxen/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:$PATH"

export MANPATH="/opt/boxen/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"
#export WORKON_HOME=$HOME/.virtualenvs
#source /opt/boxen/homebrew/share/python/virtualenvwrapper.sh

export EDITOR="atom --wait"
#export EDITOR="emacs"
export PAGER="most"

export PYTHONDONTWRITEBYTECODE=1
export PROJECT_HOME=~/Projects

export FIREFOX_BIN='/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox'

# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.3.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/mkelly/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Add personal script directory to top of path.
export PATH="/Users/mkelly/bin:$PATH"
